export const EMPLOYEE_LIST = 'EMPLOYEE_LIST';
export const ADD_EMPLOYEE = 'ADD_EMPLOYEE';
export const EDIT_EMPLOYEE_DETAIL = 'EDIT_EMPLOYEE_DETAIL';
export const DELETE_EMPLOYEE = 'DELETE_EMPLOYEE';
